export default function handler(req, res) {
  res.status(200).json({
    "2": {
      "id": "2",
      'title': '1/4" (6,4 mm) Titanium IR Drill bit',
      'model': 'DD5116',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 9,
      'cost': 9,
      'description': 'With its unique Pilot Point Tip, the DEWALT IMPACT READY® Titanium Nitride Coated Drill Bits deliver speed and clear holes with minimal burr. The feature tip helps reduce bit walking and Titanium Nitride Coating delivers long life. The optimized flute helps deliver better control of the bit and patented web taper helps increase bit strength. Ideal for metal, wood, and plastic.',
      'images': [
        'https://i.imgur.com/323Kbxi.jpg',
      ],
      'availability': 2,
    },
    "3": {
      "id": "3",
      'title': '5/16" (7,9mm) Titanium IR Drill bit',
      'model': 'DD5120',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 9,
      'cost': 9,
      'description': 'With its unique Pilot Point Tip, the DEWALT IMPACT READY® Titanium Nitride Coated Drill Bits deliver speed and clear holes with minimal burr. The feature tip helps reduce bit walking and Titanium Nitride Coating delivers long life. The optimized flute helps deliver better control of the bit and patented web taper helps increase bit strength. Ideal for metal, wood, and plastic.',
      'images': [
        'https://i.imgur.com/323Kbxi.jpg',
      ],
      'availability': 1,
    },
    "4": {
      "id": "4",
      'title': '3/8" (9,5 mm) Industrial Cobalt Drill bit',
      'model': 'DWA1224',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 9,
      'cost': 9,
      'description': 'With its unique Pilot Point Tip, the DEWALT IMPACT READY® Titanium Nitride Coated Drill Bits deliver speed and clear holes with minimal burr. The feature tip helps reduce bit walking and Titanium Nitride Coating delivers long life. The optimized flute helps deliver better control of the bit and patented web taper helps increase bit strength. Ideal for metal, wood, and plastic.',
      'images': [
        'https://i.imgur.com/323Kbxi.jpg',
      ],
      'availability': 3,
    },
    "5": {
      "id": "5",
      'title': '7/16" (11,1 mm) Industrial Cobalt Drill bit',
      'model': 'DWA1228',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 13,
      'cost': 13,
      'description': 'Built for speed and long life, DEWALT Industrial Cobalt Alloy Steel drill bits powers through hard metals with ease. Featuring the Pilot Point tip that starts on contact and eliminates bit walking helping to increase control. Heavy-duty Cobalt Alloy Steel delivers 4 times more life than black oxide.',
      'images': [
        'https://i.imgur.com/pSs954V.png',
      ],
      'availability': 2,
    },
    "6": {
      "id": "6",
      'title': '1/2" (12,7 mm) Industrial Cobalt Drill bit',
      'model': 'DWA1232',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 17,
      'cost': 17,
      'description': 'Built for speed and long life, DEWALT Industrial Cobalt Alloy Steel drill bits powers through hard metals with ease. Featuring the Pilot Point tip that starts on contact and eliminates bit walking helping to increase control. Heavy-duty Cobalt Alloy Steel delivers 4 times more life than black oxide.',
      'images': [
        'https://i.imgur.com/5NlCfCM.png',
      ],
      'availability': 2,
    },
    "7": {
      "id": "7",
      'title': '20V MAX* XR® 5Ah Battery',
      'model': 'DCB205',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 100,
      'cost': 119,
      'description': 'The DCB205 20V MAX* XR® 5.0Ah Lithium Ion Battery Pack provides immediate feedback on state of charge with the 3-LED Fuel Gauge System and has a lightweight design for easy transporting.',
      'images': [
        'https://i.imgur.com/i2j7ACt.jpg',
      ],
      'availability': 6,
    },
    "8": {
      "id": "8",
      'title': '20V MAX* XR® 6Ah Battery',
      'model': 'DCB206',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 120,
      'cost': 200,
      'description': 'The DCB206 20V MAX* 6.0Ah XR® Battery provides immediate feedback on state of charge with the 3-LED Fuel Gauge System and has a lightweight design for easy transporting.',
      'images': [
        'https://i.imgur.com/Xmb1KrK.jpg',
      ],
      'availability': 4,
    },
    "13": {
      "id": "13",
      'title': '20V MAX* Lithium Ion Compact Drill/Driver Kit',
      'model': 'DCD771',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 120,
      'cost': 169,
      'description': 'The DCD771 20V MAX* Lithium Ion Compact Drill/Driver Kit is lightweight and compact for working in tight spaces for long periods of time. High-speed transmission delivers 2-Speed variations allowing users to choose the level of performance needed for various applications.',
      'images': [
        'https://i.imgur.com/p8EQYcU.png',
      ],
      'availability': 1,
    },
    "17": {
      "id": "17",
      'title': '20V MAX* Lithium Ion 4-1/2" (115mm) / 5" (125mm) Grinder (tool only)',
      'model': 'DCG412',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 120,
      'cost': 120,
      'description': 'The DCG412B 20V MAX* Lithium Ion 4-1/2" / 5" Grinder increases productivity with features like Quick-Change™ wheel release, convenient trigger switch with lock-off button, and extended run-time battery.',
      'images': [
        'https://i.imgur.com/e5W7nG8.jpg',
      ],
      'availability': 1,
    },
    "18": {
      "id": "18",
      'title': '20V MAX* XR® 4.5 in. Paddle Switch Small Angle Grinder with Kickback Brake (tool only)',
      'model': 'DCG413',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 180,
      'cost': 180,
      'description': 'This brushless small angle grinder requires no time changing brushes, and offers a longer motor life. It offers a high level of protection. Its break stops the wheel in 2 seconds or less. The Kickback Break engages maximum force to stop the wheel when there is a pinch, stall, or bind-up to reduce kickback. The grinder will also shut off in those events to further protect the user. Battery and charger sold separately.',
      'images': [
        'https://i.imgur.com/1JqqLpP.jpg',
      ],
      'availability': 1,
    },
    "20": {
      "id": "20",
      'title': 'Metal Grinding Wheel Type 27',
      'model': 'DW4543',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 3.5,
      'cost': 3.5,
      'description': 'Featuring a soft formulation for expedited grinding of hard materials, DEWALT Type 27 Metal Grinding Wheels contain 3 full sheets of fiberglass for helps to increased durability and safety.',
      'images': [
        'https://i.imgur.com/pKXMlPp.jpg',
      ],
      'availability': 1,
    },
    "21": {
      "id": "21",
      'title': 'CROSS LINE AND PLUMB SPOTS LASER',
      'model': 'DW0822',
      'brand': 'DeWALT',
      'category': "Power Tools",
      'price': 290,
      'cost': 299,
      'description': 'The Cross Line and Plumb Spot Laser features an integrated magnetic pivoting base with quarter-inch thread front and rear mounted magnets allowing flush attachment to metal track and steel.',
      'images': [
        'https://i.imgur.com/JeBhOlV.jpg',
      ],
      'availability': 1,
    },
  })
}
